#ifndef EXCEPTIONS_H
#define EXCEPTIONS_H

enum SingularityException
{
    UNKNOWN_ERROR,
    UNDECLARED_VARIABLE,
    ARITH_EXPR_BOOLEAN_USE,
    ARITH_EXPR_FUNCTION_USE,
    ARITH_EXPR_LIST_USE,
    ARITH_EXPR_MATRIX_USE,
    ARITH_EXPR_STRING_USE,
    BOOL_EXPR_FUNCTION_USE,
    BOOL_EXPR_LIST_USE,
    BOOL_EXPR_MATRIX_USE,
    BOOL_EXPR_STRING_USE,
    BOOL_EXPR_NUM_USE,
    COMP_EXPR_BOOL_USE,
    COMP_EXPR_FUNCTION_USE,
    COMP_EXPR_LIST_USE,
    COMP_EXPR_MATRIX_USE,
    COMP_EXPR_STRING_NUM,
    VAR_CALLED_AS_FUNCTN,
    INVALID_ARG_COUNT
};

void handleException(SingularityException exception);

#endif // EXCEPTIONS_H